import { Milestone, Memory, LoveNote, UserSettings } from '../types';

export const DEFAULT_SETTINGS: UserSettings = {
  startDate: '2023-05-20',
  partner1: 'Alex',
  partner2: 'Jamie',
  catName: 'Mochi',
  avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDzz20depciI1E4xQB8bNanaiMnKCbIqQq0xtS6SNbKuQqXC7XWKF4T6PYZNMNnU8EwF1PkIiTGKocn8oQHlbNpy2-H-_0FNc4Vr2ZJQSjCTuevqZWfnzgojHHfsb4DhHYjy-xbRMZ8sCRTyy80x2mtYriAmAlGmAOprQX3ZKB2SEK4PjYIooKyircVD3GekH1U4i2cchQajazRmGD6uqCZsTP3JQknjmyVYviqYR0qDZv3nNg9Q1WD',
  soundEnabled: true,
  darkMode: false,
};

export const HERO_IMAGE = 'https://lh3.googleusercontent.com/aida-public/AB6AXuCUF2rpIYtcz5C_iiJmWImsgvdbQmNkOlyI8av4h_mojY6ssOSiwmEAhP7Jy4b_T9ud2IVWk9anC_x83vfucQnJ3qSnV9EUBbrjvuPzl4FyuuSBluCrioTJT_-P06_wVvbaUma9yxT9IxdMoBMYyNRR73tnYmN4ta3E04eYr5tMqdimPeWSPMYkmKqc-n5LBeXITMLM1WIteZuQ2T2of0uGm9qT9-DCRTCeF0CaSRY43aIG0FwFU9qv';

export const PIXEL_CAT_IMAGE = 'https://lh3.googleusercontent.com/aida-public/AB6AXuDz0fUDuf_tm8uMkdsxkpaj7vHqDCVkDd0Gfv1IW9IHcvToNt3GDdKqLLjMx5VliNBs9sXyxRO7z7tfyOXbjN7-JQCnOeEwGLRcIErHwHDbKZUNSqg__WhD5NmjrACgudzXpwmGOHhf5IUUyTIAnCXj6FMi_esD_zOcun3s0dF40GTfQdzaXqAE_hqDwV4r3Zj_lK0RP07rz9wQtAMA85a1Tf-tbdlkQw8C-nRpf647R5FLpAXmwKkb';

export const CAT_QUOTES = [
  "你是我最喜欢的人！✨",
  "喵呜！今天给我准备小鱼干了吗？🐟",
  "呼噜呼噜... 和你在一起的每一天都很甜！🐾",
  "今天也要记得多喝水、保持好心情哦！☕",
  "正在发射 100x 像素小爱心！❤️",
  "别忘了我们是世界上最好的拍档！🎮",
  "Mochi 最喜欢看你笑啦！🐱",
  "520% 的爱意正在加载中... 满格！💖"
];

export const DEFAULT_MILESTONES: Milestone[] = [
  {
    id: 'm-1',
    date: '2023.05.20',
    title: '初次相遇的那天',
    description: '在市中心那家安静的街角咖啡馆，紧张地说了第一声你好。咖啡渐渐凉了，但我们的故事才刚刚开始。',
    category: 'meet',
    icon: 'pets',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAqn8D7c1bycbjpbcWaHcOa_lRgFZ6P8eHm8ouwuNWHM4N4lvaiK7a9qf2xUTl7vht49r7cMDuBGXilN4TFTgwcJqnB2FMUr5TVtskqisCPX_-A-d_PYZA5dQ1tW9A9sWmZ1jpnPu33I0i9JHjlqX3PsRwjQ5r_ijSuEmD3APUjJGkcSzdFrND7720N0uUr9BedZC0HTYOD_pXm4UDpXuAbwoZ3IdJfNgxRoj4CRw-7T8hHDC0EQjoS',
    likes: 128,
  },
  {
    id: 'm-2',
    date: '2023.08.15',
    title: '我们的第一次旅行',
    description: '收拾好行囊，一直开到地图的尽头。虽然迷路了一小会儿，却成了这段旅程中最浪漫的意外。',
    category: 'trip',
    icon: 'flight_takeoff',
    likes: 99,
  },
  {
    id: 'm-3',
    date: '2023.11.01',
    title: '欢迎 Mochi 来到我们的小家',
    description: '一个毛茸茸的小家伙闯进了我们的生活，并永远霸占了沙发上最暖和的角落。',
    category: 'cat',
    icon: 'cruelty_free',
    likes: 256,
  },
  {
    id: 'm-4',
    date: '2024.02.14',
    title: "你说「我愿意」的那一刻",
    description: '在漫天繁星和一轮温柔的像素月亮下，许下了一起把这个故事一帧一帧写下去的约定。',
    category: 'love',
    icon: 'favorite',
    likes: 520,
  }
];

export const DEFAULT_MEMORIES: Memory[] = [
  {
    id: 'mem-1',
    title: '周日清晨的咖啡',
    description: '街角咖啡馆的周日清晨。咖啡师终于拉出了超可爱的猫咪拉花！',
    date: '2023.10.12',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA-nAS9TinbU3RDOYbZWO6_Ac4h1Zl1onP-ce2eI-vcWLDJDFcTKa7cVyZEPQp5xd3OgrSoOOZLvPW-cltyDwLHFbovApLjYLd52FTBUj_PkCV012qR64VoQQSt36ErK08YQK5benRuA3UGAeGur2bSELg5EBjst4ffbu_-ZOtFZj1kikWtEK4YjTpzYlljO7onKnRRpIuCfEyv0DccZaHqhsY2jrd1FDq2DlJSCMb73byqlKTd6dhV',
    category: 'cafe',
    aspectRatio: 'square',
    likes: 42,
    isLiked: false,
    tapeColor: 'pink',
    tapeRotation: -2,
  },
  {
    id: 'mem-2',
    title: '熟睡中的小猫',
    description: '小猫最喜欢的睡觉宝地，嘘，千万别吵醒它~',
    date: '2023.11.04',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuApNbXTjKLlKPOgQgA9UQTEuPiUPTN-qXbvcwUBnCIWLxeVVOF9RG9mXdD_Ef6ncRk0hCV3ClcO_ptVdZaxnpKRL5byojSdEB8tySvM5qbGP1NWrQOVtQ7wRXDwRwWDdw-W4VfzSzDG6joCmB6ngq6sN2pLIkrUGXp2kKaaN_VBme-fJLY-pjQnOYYoKzSvh2jxfjWpwAxpud_395urJuLtAm8eIswKVkKShvQXdC8t0NWCFGAxdzC8',
    category: 'cat',
    aspectRatio: 'portrait',
    likes: 88,
    isLiked: true,
    tapeColor: 'lavender',
    tapeRotation: 4,
  },
  {
    id: 'mem-3',
    title: '夕阳下的公园漫步',
    description: '走到脚酸也不想停下，心里装满了温柔与日落。',
    date: '2023.09.28',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAGpguA_1Dyp6Ab6KQNIr2HUcaY5qhoWekUg0nCND2FAb-me4lztrtJOFBRlXfJw_o8GBmJi9sX0q2hT5q6Z8q2Q7PTn6NUn7sINrHf0PFWxgXgNrk_Vq8HpUCxGv9lZlsDi7Z7D9Uznf8QhZ2wDE4R29SsG3tpo_MHyYMwl_2H3yIcq_p6CyL9TWe8M7z7nIFK508qiAQ_xKiIy2S8ELHdxC7cQFTl5UagbKmh5AUyCjbwUuqeD9BN',
    category: 'trip',
    aspectRatio: 'landscape',
    likes: 67,
    isLiked: false,
    tapeColor: 'mint',
    tapeRotation: -5,
  },
  {
    id: 'mem-4',
    title: '突然送上的小雏菊',
    description: '没有特别理由送的花，往往是最开心的惊喜。🌼',
    date: '2023.08.15',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCJheWZVRrJ5QnUzZ6-0cf5nmA9jY1q9TI3ztIw7s46mNuXJOOP1y7-8cYmIINeSod88MaFMx2-gEVJVaWWsDXjaHLI08M-vbD4BBxJ-VuZkgFdlBZh4_ndF5M-H5A3aCxopA5IgevBCbopLhIwGwiigv4peFtGu4IA4bI-GqUA-6NNiwjnwierEnbXRa_5fBEsAYsvs-157zPAzKVIXOFJpkClIyem9cRiHiKABGBkmQ6MEUDcrvOf',
    category: 'gift',
    aspectRatio: 'portrait',
    likes: 95,
    isLiked: true,
    tapeColor: 'pink',
    tapeRotation: 1,
  },
  {
    id: 'mem-5',
    title: '淘到的复古胶片机',
    description: '试拍新淘到的复古胶片机，准备好记录我们生活里的所有琐碎与美好。',
    date: '2023.07.02',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBswR5bxe35HUOQKKXiJy8SOyDdKQrQvsgf5eGKxl96Qkh-WkTJup073Y1ZIS7oa3jvED3kr7jmulhCE9q4GCfKL0v6p3S_1Bg1PEoBFqww7vNS_mAbnnwgCAnZHreJvlt0yGzYF9JOJte92uMm10-k8iyAoY-7OvYg1407L5iY0J4OseaI-kk3gRcaaxuQCPHGFyRQGe8OjI6gtI9O-HA12cO5nMwM7p-xSxp2N5EJipyIhmggxgzw',
    category: 'daily',
    aspectRatio: 'square',
    likes: 53,
    isLiked: false,
    tapeColor: 'lavender',
    tapeRotation: -3,
  }
];

export const DEFAULT_LOVE_NOTES: LoveNote[] = [
  {
    id: 'note-1',
    author: 'Alex',
    content: '还在回味街角小店的咖啡香，已经开始期待下周末的约会啦。☕✨',
    date: '2小时前',
    mood: '浪漫约会',
    moodIcon: 'favorite',
    bgColor: 'pink',
    rotation: -1.5,
    likes: 12,
    isLiked: false,
  },
  {
    id: 'note-2',
    author: 'Jamie',
    content: '别忘了下班买猫粮！另外，我爱你胜过爱世界上所有的芝士披萨。🍕🐾',
    date: '1天前',
    mood: '日常提醒',
    moodIcon: 'cruelty_free',
    bgColor: 'mint',
    rotation: 2,
    likes: 24,
    isLiked: true,
  },
  {
    id: 'note-3',
    author: 'Alex',
    content: '快看，不知道哪只小猪又睡在你这半边床上啦...',
    date: '周二 14:20',
    mood: '猫咪抓拍',
    moodIcon: 'photo_camera',
    bgColor: 'cream',
    rotation: -2,
    likes: 31,
    isLiked: false,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDncPSJD8c8dTMhLm-MYUUIX4H9BE6T5DDhTPWIx9pshYKVkrHngXEevPpvUXj1OXCT-vOAO1bnyMqu1pbZ08wSYEJxu8xMyQ6x20wr9S2vg5FJiCGMh2XOutLFh2pmNVZKN5vMyhkPqEqnhwaZRmKND_qVp6p-aPQMb_6npfj60GskUWLHcr2mKrtaVv_Ps-MjROm2eNOzA8koLKFeaEPE0HM1DQIE9VK0yBs583pzF9acbQPsENk-',
  },
  {
    id: 'note-4',
    author: 'Jamie',
    content: '正在倒数周年纪念旅行的日子，我偷偷准备好几个神秘惊喜啦！✨✈️',
    date: '1周前',
    mood: '神秘旅行',
    moodIcon: 'flight_takeoff',
    bgColor: 'lavender',
    rotation: 1.2,
    likes: 19,
    isLiked: false,
  },
  {
    id: 'note-5',
    author: 'Alex',
    content: '「你是我世界上最喜欢的特别关注与消息提示音。」📱❤️',
    date: '3月12日',
    mood: '甜蜜情话',
    moodIcon: 'favorite',
    bgColor: 'pink',
    rotation: -2.8,
    likes: 45,
    isLiked: true,
    isPinned: true,
  }
];
